name: mozika
description: A WCC project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  file_picker: ^5.3.2
  shared_preferences: ^2.2.0
  path: ^1.8.3
  path_provider: ^2.0.15
  dartz: ^0.10.1
  flutter_riverpod: ^2.3.6
  audioplayers: ^4.1.0
  dart_tags: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true